/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "secondary-fixed-dim": "#bdc7d8",
        "on-surface": "#261817",
        "surface-tint": "#b52330",
        "on-primary-fixed-variant": "#92001b",
        "outline": "#8e706f",
        "outline-variant": "#e2bebc",
        "secondary-fixed": "#d9e3f4",
        "tertiary": "#006c4c",
        "primary": "#b52330",
        "primary-fixed-dim": "#ffb3b0",
        "on-primary-fixed": "#410007",
        "primary-container": "#ff5a5f",
        "surface-container-highest": "#f7dcdb",
        "primary-fixed": "#ffdad8",
        "secondary-container": "#d6e0f1",
        "tertiary-fixed-dim": "#59ddaa",
        "surface-bright": "#fff8f7",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "on-primary-container": "#61000e",
        "surface": "#fff8f7",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#596372",
        "background": "#fff8f7",
        "tertiary-fixed": "#78fac4",
        "surface-dim": "#efd4d2",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#003423",
        "on-secondary-fixed-variant": "#3e4755",
        "error": "#ba1a1a",
        "tertiary-container": "#00a879",
        "surface-variant": "#f7dcdb",
        "on-background": "#261817",
        "secondary": "#555f6d",
        "inverse-primary": "#ffb3b0",
        "inverse-on-surface": "#ffedeb",
        "surface-container": "#ffe9e7",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#005139",
        "surface-container-low": "#fff0ef",
        "on-secondary-fixed": "#121c28",
        "inverse-surface": "#3d2c2c",
        "surface-container-high": "#fde2e0",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#5a403f",
        "on-tertiary-fixed": "#002115"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "margin_desktop": "24px",
        "xl": "32px",
        "unit": "4px",
        "sm": "8px",
        "container_max_width": "1200px",
        "margin_mobile": "16px",
        "gutter": "16px",
        "xs": "4px",
        "md": "16px",
        "xxl": "48px",
        "lg": "24px"
      },
      "fontFamily": {
        "h2": ["Plus Jakarta Sans"],
        "label-md": ["Be Vietnam Pro"],
        "body-md": ["Be Vietnam Pro"],
        "body-sm": ["Be Vietnam Pro"],
        "body-lg": ["Be Vietnam Pro"],
        "label-sm": ["Be Vietnam Pro"],
        "h3": ["Plus Jakarta Sans"],
        "h1": ["Plus Jakarta Sans"],
        "display": ["Plus Jakarta Sans"]
      },
      "fontSize": {
        "h2": ["24px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "1.2", "letterSpacing": "0.04em", "fontWeight": "500" }],
        "h3": ["20px", { "lineHeight": "1.4", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "h1": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "display": ["40px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }]
      }
    }
  },
  plugins: [],
}
